apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-kafka-init-cm
  namespace: {{ .Values.namespace }}

data:
  kafka_topics.json: |
    {{- .Values.kafkaInfrastructure | toJson | nindent 4 }}

  kafka_init.py: |
{{ .Files.Get "scripts/init.py" | indent 4 }}

  init-topics.sh: |
    #!/bin/sh
    {{- range .Values.kafkaInfrastructure.topics }}
    /opt/kafka/bin/kafka-topics.sh \
      --bootstrap-server localhost:9092 \
      --create \
      --if-not-exists \
      --topic "{{ .name }}" \
      --partitions {{ .partitions }} \
      --replication-factor {{ .replicationFactor }} \
      {{- range $key, $value := .configs }}
      --config {{ $key }}="{{ $value }}" \
      {{- end }}
      ;
    {{- end }}