apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-service
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Release.Name }}-{{ .Chart.Name }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Release.Name }}-{{ .Chart.Name }}
  ports:
    - name: {{ .Values.service.http.name }}
      port: {{ .Values.service.http.port }}
      targetPort: {{ .Values.service.http.targetPort }}
    - name: {{ .Values.service.grpc.name }}
      port: {{ .Values.service.grpc.port }}
      targetPort: {{ .Values.service.grpc.targetPort }}
    - name: {{ .Values.service.metrics.name }}
      port: {{ .Values.service.metrics.port }}
      targetPort: {{ .Values.service.metrics.targetPort }}

---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-http-service
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Release.Name }}-{{ .Chart.Name }}
spec:
  type: {{ .Values.serviceHttp.type }}
  selector:
    app: {{ .Release.Name }}-{{ .Chart.Name }}
  ports:
    - name: http
      port: {{ .Values.serviceHttp.port }}
      targetPort: {{ .Values.serviceHttp.targetPort }}