{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-sm
  namespace: {{ .Values.namespace }}
  labels:
    release: {{ .Values.serviceMonitor.releaseLabel }}
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  namespaceSelector:
    matchNames:
      - {{ .Values.namespace }}
  endpoints:
  - port: metrics
    path: {{ .Values.serviceMonitor.path }}
    interval: {{ .Values.serviceMonitor.interval }}
    scrapeTimeout: {{ .Values.serviceMonitor.scrapeTimeout }}
{{- end }}